### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by mion00**
This PR updates the `README` files and move the documentation of the addon under the `Docs.md` file, that is made available inside HA UI in the `Documentation` tab of the addon.
I merge this directly in `main` since this documentation is about the current version of the addon, not the new version in `dev`.

### CODE REVIEW

**Comment by pergolafabio** [comment]
Looks ok?
Do now we can delete all branches and only use dev?

**Comment by mion00** [comment]
You mean we keep `main` as the golden standard containing always the latest release, and merge all development work on `dev`?

**Comment by pergolafabio** [comment]
Yes indeed?

**Comment by pergolafabio** [comment]
maybe its better to change slug name also, then users need to offcourse reinstall again, but so be it :-)

**Comment by pergolafabio** [comment]
maybe as a breaking change next time

**Comment by mion00** [comment]
Yeah I am thinking of changing it in the dev branch

**Pull request merged**
