### PR TITLE
Keep retrying when connection to doorbell fails

### LINKED ISSUE #223: The add-on exits when it loses connectivity with the doorbell
### What happened?

Every time power goes out for some time, the add-on exits because it loses connectivity with the doorbell, and I must manually start it (even though supervisor watchdog is enabled for it).

This is bad, as not always I will be available to "fix" this situation that other house members may encounter.

In my opinion, the add-on should never exit (except in case the config cannot be parsed for example). It should keep retrying forever to connect with the doorbell.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.15

### Installation type

Home Assistant add-on

### Relevant log output

```Text
2024-09-28 18:04:27.592 | INFO     | event:motion_detection:98 - Motion detected from Vídeo porteiro
2024-09-28 18:09:28.797 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2024-09-28 18:09:28.797 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2024-09-28 18:09:28.825 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 1 ip
2024-09-28 18:09:31.984 | ERROR    | __main__:<module>:101 - Error while logging into Vídeo porteiro: Failed to connect to the device. The device is off-line, or connection timeout caused by network. Error code:7
2024-09-28 18:09:32.551 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2024-09-28 18:09:32.551 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2024-09-28 18:09:32.559 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 1 ip
2024-09-28 18:09:35.055 | ERROR    | __main__:<module>:101 - Error while logging into Vídeo porteiro: Failed to connect to the device. The device is off-line, or connection timeout caused by network. Error code:7
2024-09-28 18:09:35.586 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2024-09-28 18:09:35.586 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2024-09-28 18:09:35.594 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 1 ip
2024-09-28 18:09:38.128 | ERROR    | __main__:<module>:101 - Error while logging into Vídeo porteiro: Failed to connect to the device. The device is off-line, or connection timeout caused by network. Error code:7
2024-09-28 18:09:38.685 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2024-09-28 18:09:38.685 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2024-09-28 18:09:38.692 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 1 ip
2024-09-28 18:09:41.840 | ERROR    | __main__:<module>:101 - Error while logging into Vídeo porteiro: Failed to connect to the device. The device is off-line, or connection timeout caused by network. Error code:7
2024-09-28 18:09:42.397 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2024-09-28 18:09:42.397 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2024-09-28 18:09:42.404 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 1 ip
2024-09-28 18:09:44.913 | ERROR    | __main__:<module>:101 - Error while logging into Vídeo porteiro: Failed to connect to the device. The device is off-line, or connection timeout caused by network. Error code:7
2024-09-28 18:09:45.474 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2024-09-28 18:09:45.474 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2024-09-28 18:09:45.481 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 1 ip
2024-09-28 18:09:48.367 | ERROR    | __main__:<module>:101 - Error while logging into Vídeo porteiro: Failed to connect to the device. The device is off-line, or connection timeout caused by network. Error code:7
2024-09-28 18:09:48.932 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2024-09-28 18:09:48.932 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2024-09-28 18:09:48.939 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 1 ip
2024-09-28 18:09:52.080 | ERROR    | __main__:<module>:101 - Error while logging into Vídeo porteiro: Failed to connect to the device. The device is off-line, or connection timeout caused by network. Error code:7
2024-09-28 18:09:52.793 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2024-09-28 18:09:52.793 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2024-09-28 18:09:52.800 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 1 ip
2024-09-28 18:09:55.152 | ERROR    | __main__:<module>:101 - Error while logging into Vídeo porteiro: Failed to connect to the device. The device is off-line, or connection timeout caused by network. Error code:7
2024-09-28 18:09:55.702 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2024-09-28 18:09:55.702 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2024-09-28 18:09:55.710 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 1 ip
2024-09-28 18:09:58.608 | ERROR    | __main__:<module>:101 - Error while logging into Vídeo porteiro: Failed to connect to the device. The device is off-line, or connection timeout caused by network. Error code:7
2024-09-28 18:09:59.189 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2024-09-28 18:09:59.189 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2024-09-28 18:09:59.196 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 1 ip
2024-09-28 18:10:02.320 | ERROR    | __main__:<module>:101 - Error while logging into Vídeo porteiro: Failed to connect to the device. The device is off-line, or connection timeout caused by network. Error code:7
2024-09-28 18:10:02.879 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2024-09-28 18:10:02.879 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2024-09-28 18:10:02.887 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 1 ip
2024-09-28 18:10:05.392 | ERROR    | __main__:<module>:101 - Error while logging into Vídeo porteiro: Failed to connect to the device. The device is off-line, or connection timeout caused by network. Error code:7
```

### Relevant configuration

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by felipecrs**
Closes #223

### CODE REVIEW

**Comment by felipecrs** [comment]
@pergolafabio, I did not try it yet, but I think it should work.

**Comment by pergolafabio** [comment]
Hey, did a test agian
addon was connected, rebooted my indoor device, and it came back online without the need of restarting the addon:

image

**Comment by pergolafabio** [comment]
i see error 7 , if the device is in an offline state, and you start the addon at that point

**Comment by pergolafabio** [comment]
i added beta 68 with your changed code, to handle error 7
can you install the beta 68 and test it?

**Comment by felipecrs** [comment]
It worked!

image

**Comment by pergolafabio** [comment]
perfect :-)

**Pull request closed without merging**
