### PR TITLE
Multi-architecture build

### PR DESCRIPTION
**Pull request by mion00**
Avoid splitting the codebase in two folders, one for amd64 and one for aarch64. This pull request allows to build two distinct Docker images using the build.yaml feature offered by Home Assistant (https://developers.home-assistant.io/docs/add-ons/configuration#add-on-extended-build).
The correct Hikvision library is copied at build time inside the container, based on the target architecture.
In the end a single addon is available for the end user, greatly simplifying the setup.

There is in addition a new config.py file that can read the required configuration from the environment variables, in addition to the JSON file provided inside the addon. This is useful to locally develop and debug the addon, without having to modify any file and reloading it every time inside HA.
P.S.: Fantastic job getting the SDK up and running with the doorbells!

### CODE REVIEW

**Comment by pergolafabio** [comment]
Aha! Great, yeah, I'm not a developer and not really familiar with GitHub/docker but was doing the best I can, this is indeed much better... I hale a look later...

I think it's missing the second IP to define the indoor panel, for sending the callsignal too...

Q: now I let the users create template sensors, do you think it's also possible that this addon can create sensors  upon start?

**Comment by mion00** [comment]
Yeah sorry I forgot about the second IP! That is why I put in draft mode the pull request :wink:. I will add it as soon as possible!
Regarding the sensors, sure I have some ideas I would like to share with you. Why don't we discuss toghether by opening an issue here on Github? That way we can track separately the conversation and make a plan for the changes.

**Comment by pergolafabio** [comment]
Great!! Are you also on discord? Do you also use the Hikvision sip ? We have a dedicated asterisk channel and also separate hikvision section

**Comment by pergolafabio** [comment]
On my roadmqap was also the idea to input multiple doorstations, now they need to installed a second addon

**Comment by mion00** [comment]
> On my roadmqap was also the idea to input multiple doorstations, now they need to installed a second addon

I was thinking the same thing! :wink: I also had some ideas in mind on how to handle multiple connections with a sort of middleware "device manager", one for each doorbell.

**Comment by mion00** [comment]
> Great!! Are you also on discord? Do you also use the Hikvision sip ? We have a dedicated asterisk channel and also separate hikvision section

Do you mean the general home assistant Discord? I don't see `hikvision` in the channel list.

**Comment by pergolafabio** [comment]
> > Great!! Are you also on discord? Do you also use the Hikvision sip ? We have a dedicated asterisk channel and also separate hikvision section
> 
> Do you mean the general home assistant Discord? I don't see `hikvision` in the channel list.

No, in the asterisk channel, I send you link later,

**Comment by pergolafabio** [comment]
> > Great!! Are you also on discord? Do you also use the Hikvision sip ? We have a dedicated asterisk channel and also separate hikvision section
> 
> Do you mean the general home assistant Discord? I don't see `hikvision` in the channel list.

here is link : https://discord.gg/BbF6qPNQ

**Comment by mion00** [comment]
I think this PR is ready to proceed, if you want to merge it.

**Pull request merged**
