### PR TITLE
Feat: MQTT integration

### PR DESCRIPTION
**Pull request by mion00**
Thanks to the library [ha-mqtt-discoverable](https://github.com/unixorn/ha-mqtt-discoverable) it is possible to define HA entities in Python that are automatically added to HA, using its internal MQTT discovery implementation.

## Description

- Add configuration options for defining the connection to the broker
  - If the user is running this as an HA add-on and has already a MQTT integration set-up, automatically load the connection settings using the `supervisor/services/mqtt` API
- Update the documentation instruction to explain how to setup the `mosquitto` add-on broker, required for this integration to work.
- Explained the two integration methods available for HA:
  - MQTT
  - REST API (activated automatically if MQTT is not available)
- Add HA buttons for rebooting, accepting and rejecting calls
- Add `Call state` sensor to display the state of the doorbell (idle, ringing, dismissed)
- In case HA restarts and this add-on has trouble communicating with the doorbells, instead of having the sensors disappear completely they now show up in HA as `unavailable`

Some users already encountered the limits of using REST API, for instance:
- the entities are gone after HA restarts
- no possibility to customize the entities via the UI, due to missing `unique_id`

Should we encourage users to migrate from the REST API to MQTT? This way we avoid duplicating our effort on maintaining and troubleshooting two separate way to communicate with HA.

### CODE REVIEW

**Review by mion00 — COMMENTED** [review]
Wait, there is a bit of fallacy in the code: the exception is always raised in line 108, regardless of result from line 104.
Allow me to fix that.

**Comment by mion00** [comment]
I think next week we should take a moment and decide to release this version as beta, otherwise it's a continual adding of bugfix on top of bugfix. The users meanwhile report bugs on a beta version based on REST API that we are deprecating, so tracking what gets fixed where is a bit messy. :sweat_smile: 
I suggest we release this (checking the docs are ok, users now need an MQTT broker), so we get a first round of feedbacks and fix the bugs with this new codebase.

**Comment by pergolafabio** [comment]
Yeah, was thinking the same, for me, first beta, and maybe already final too, stable enough!!

I was testing the jpeg capture, then making the snapshots appear on an mqtt camera.... Eventually also bringing a live stream to it,

**Comment by pergolafabio** [comment]
Maybe merge the 2 new branches already in dev, maybe together with the new SDK...

So I can test again and run it a day before beta?

**Comment by mion00** [comment]
> Maybe merge the 2 new branches already in dev, maybe together with the new SDK...
> 
> So I can test again and run it a day before beta?

Ok will do later.
I saw jpeg capture. Is it an event coming from doorbell or manually called?
Mine doesn't do seem to generate an event.

**Comment by pergolafabio** [comment]
Manually called indeed

**Comment by mion00** [comment]
Pulling the trigger on this. Full steam ahead! :steam_locomotive:

**Comment by pergolafabio** [comment]
yeah, i cant follow  you!!

**Comment by pergolafabio** [comment]
maybe just release beta; so its gets fixed for Pepe :-) , the addon works

**Comment by mion00** [comment]
> maybe just release beta; so its gets fixed for Pepe :-) , the addon works

Yeah, was thinking the same. Poor user is going crazy with the local add-on issues.. :sweat_smile:

**Pull request merged**
