### PR TITLE
External broker settings

### LINKED ISSUE #93: Allow setting mqtt options
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Python can correctly read the mqtt config, but the addon metadata in HA must be updated to allow those options.

### PR DESCRIPTION
**Pull request by mion00**
Allow the user of the add-on to use an external MQTT broker.
I cannot test this in my local environment due to an issue with the upstream VSCode devcontainer, so I am not 100% sure it works as designed.

Fixes #93

### CODE REVIEW

**Comment by pergolafabio** [comment]
Just tested , if i dont provide any MQTT settings in the addon config, i see now this:

`2023-06-28 20:57:28.562 | WARNING  | event:start:238 - No handler defined!`

and it doesnt start

**Comment by pergolafabio** [comment]
If i a define, it starts correctly

if i now define a wrong ip to the broker, it now reports and error, thats indeed better
maybe also when users enter a wrong portt? or maybe some auth issues in case  of wrong username/password?

**Comment by mion00** [comment]
> Just tested , if i dont provide any MQTT settings in the addon config, i see now this:
> 
> `2023-06-28 20:57:28.562 | WARNING | event:start:238 - No handler defined!`
> 
> and it doesnt start

Do you have the MQTT addon installed? It should automatically load the host and port by asking the supervisor API.

**Comment by pergolafabio** [comment]
yeah, i have the mqtt addon, this branch worked yesterday, i tested it , seens now with the 2 extar commits, it doesnt want to start anymore, if i leave the mqtt section empty

**Comment by mion00** [comment]
For checking the user/password, I need to setup a broker with authentication locally first.
For the connection port, I need to modify the MQTT library to allow the settings of a custom port.

**Comment by pergolafabio** [comment]
i commented this, and now seems to work,

wheno mqtt option is present in the config , it now starts

```
        # If we have no value in input, skip validation
        # if not v:
            # return
```

**Comment by mion00** [comment]
> yeah, i have the mqtt addon, this branch worked yesterday, i tested it , seens now with the 2 extar commits, it doesnt want to start anymore, if i leave the mqtt section empty

Ok, I will see if I can setup a local environment for the add-on to see what is happening under the hood.

**Comment by mion00** [comment]
It should now work correctly, with my limited testing.

**Comment by pergolafabio** [comment]
Hey @mion00 , if you want, you can release a new beta... Do we also need to add some manual Mqtt instructions on the main branch?

I have limited time, on vacation as you now in Puglia :-)

Maybe this can be released together with the other 2 branches for zone alarm and door open device trigger?

I think maybe the only one left is to make 8000 port configurable, some people were asking for it, maybe after that one, it's time to make an official new release

**Comment by pergolafabio** [comment]
i have tested this one locally, it works now indeed!

**Pull request merged**
